### ISSUE TITLE
Failed to compile the project with maven

### ISSUE THREAD

**Issue by Rqcker** [RAINS-UOA/rains-workflow-builder#7]
**Describe the problem:**
When I finished creating the GraphDB repository, I used git to clone the project to the local directory. When I use maven, a file cannot be found error will cause the compilation to fail, and the result will not be displayed on the GraphDB on the web side. The error screenshot is as follows:

![image](https://user-images.githubusercontent.com/20661419/125848335-0553e322-3e85-4e2c-bc4f-ff4353e037ff.png)

**The question shows that the files in the rains-workflow-builder/rains-workflow-builder/src/main/java/uoa/web/handlers/SystemRecordManager.java:[49,30] package org.omg.CORBA.portable directory are not exist.**

![image](https://user-images.githubusercontent.com/20661419/125848832-46e3e126-5a51-4f12-90ff-9d2e6330c3f2.png)

This is a screenshot of the interface where I found the target file

**Comment by inaja** [comment]
Yes, sometimes line 49 fails to compile (it never compiled for me but it does not give Milan problems), comment it for now and try to compile again, as far as I can tell, it is not used, it is from previous things that are now commented out.

**Comment by Rqcker** [comment]
Cheers, thank you for your help, it is really useful! Now it can run successfully.
![image](https://user-images.githubusercontent.com/20661419/126184598-f06219b9-695c-459f-9dd3-a8eee745f103.png)
8080:
![image](https://user-images.githubusercontent.com/20661419/126184637-de14e3a4-40a5-4c69-aa15-4a0ecc5e0a52.png)
